#!/bin/sh
echo "Loaded Dvcky QAI!"
read -p "Press enter to continue..."
timedatectl set-ntp true



# ----PARTITIONING----

# GET USER INPUT
fdisk -l
read -p "Enter drive to install arch here: " drive
fdisk $drive
fdisk -l $drive
read -p "Enter boot partition: " boot_part
read -p "Enter system partition: " sys_part

# SYSTEM PARTITION (+ENCRYPTION)
cryptsetup -y -v luksFormat $sys_part
cryptsetup open $sys_part root
mkfs.ext4 /dev/mapper/root
mount /dev/mapper/root /mnt

# BOOT PARTITION
mkfs.fat -F32 $boot_part
mount --mkdir $boot_part /mnt/boot

# --------



# ----REPOSITORIES----

pacman -Syu archlinux-keyring

# --------



# ----PACKAGES----

pacstrap /mnt base base-devel linux linux-firmware neovim

# --------




genfstab -U /mnt >> /mnt/etc/fstab
curl -Lo 2 dvcky.github.io/arch/2
mv 2 /mnt/2
rm 1
arch-chroot /mnt sh 2
