#!/bin/sh



# ----SYSTEM----

#SET TIMEZONE AND CLOCK
ln -sf /usr/share/zoneinfo/America/Chicago /etc/localtime
hwclock --systohc

#SET LOCALE
sed -i "s/#en_US\.UTF-8/en_US\.UTF-8/" /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf

#SET SYSTEM NAME
echo "arch" > /etc/hostname

#EDIT ROOT USER
echo --SET ROOT USER PASSWORD--
passwd

# --------



# ----REPOSITORIES----

# ENABLE MULTILIB REPO
sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf

# UPDATE/APPLY CHANGES
pacman -Syu archlinux-keyring

# --------



# ----PACKAGES----

# ENABLE ENCRYPTION KERNEL MODULE
sed -i "s/consolefont block filesystems/consolefont block encrypt filesystems/" /etc/mkinitcpio.conf

# DOWNLOAD PACKAGES
pacman -Sy docker efibootmgr flatpak flatpak-kcm git sudo \
mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon libva-mesa-driver lib32-libva-mesa-driver mesa-vdpau lib32-mesa-vdpau \
pipewire lib32-pipewire wireplumber pipewire-audio pipewire-alsa pipewire-pulse pipewire-jack lib32-pipewire-jack \
plasma-meta ark p7zip unarchiver dolphin ffmpegthumbs kdegraphics-thumbnailers kio-admin konsole kwrite kvantum partitionmanager spectacle firefox keepassxc lutris mpv noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra qbittorrent steam ttf-nerd-fonts-symbols

# POST-INSTALL PARU PACKAGES: paru-bin (mullvad-vpn-bin && vscodium-bin), with flatpak (nicotine+ && qview && tauon-music-box)

# IMPROVE FONT SUPPORT
curl -Lo /etc/fonts/local.conf dvcky.github.io/arch/fontconfig

# --------



# ----USER----

echo --CREATE NORMAL USER--
read -p "Username: " uname
useradd -mG wheel $uname
passwd $uname

# ADDITIONALLY, ALLOW STANDARD USER TO USE SUDO

EDITOR=nvim visudo

# --------



# ----SERVICES----

# DISPLAY MANAGER
systemctl enable sddm

# WIRELESS CONNECTIVITY
systemctl enable NetworkManager
systemctl enable bluetooth

# DOCKER
systemctl enable docker

# --------

echo "Now create your boot entry! Example: \"efibootmgr --create --disk /dev/nvme0n1 --part 1 --label \"arch\" --loader /vmlinuz-linux --unicode 'cryptdevice=/dev/nvme0n1p2:root root=/dev/mapper/root rw quiet initrd=\initramfs-linux.img'\""

rm 2
