#!/bin/sh
echo Running chroot, loaded DvckyQAI2!

#SET TIMEZONE AND CLOCK
ln -sf /usr/share/zoneinfo/America/Chicago /etc/localtime
hwclock --systohc

#SET LOCALE
sed -i "s/#en_US\.UTF-8/en_US\.UTF-8/" /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf

#SET SYSTEM NAME
echo "arch" > /etc/hostname

#EDIT ROOT USER
echo --SET ROOT USER PASSWORD--
passwd

#ENABLE MULTILIB REPO AND UPDATE
sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf

pacman-key --init
pacman-key --populate archlinux
echo "Server = https://america.archive.pkgbuild.com/repos/month/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
pacman -Syyuu archlinux-keyring

sed -i "s/consolefont block filesystems/consolefont block encrypt filesystems/" /etc/mkinitcpio.conf
# DOWNLOAD PACKAGES
pacman -Sy mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon libva-mesa-driver lib32-libva-mesa-driver mesa-vdpau lib32-mesa-vdpau pipewire lib32-pipewire wireplumber pipewire-alsa pipewire-pulse pipewire-jack lib32-pipewire-jack phonon-qt5-gstreamer ark bluedevil breeze-gtk dolphin drkonqi kde-gtk-config kdegraphics-thumbnailers kdeplasma-addons khotkeys konsole kwrite kwrited kscreen kvantum kwallet-pam kwalletmanager partitionmanager plasma-desktop plasma-nm plasma-pa plasma-systemmonitor plasma-wayland-session powerdevil sddm-kcm spectacle xdg-desktop-portal-kde docker dosfstools efibootmgr ffmpegthumbs firefox git icoutils keepassxc lutris mpv noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra steam sudo syncthing ttf-nerd-fonts-symbols unrar
#pacman -S alacritty blueman bspwm btop curl dmenu dunst efibootmgr feh git gparted grub gvfs gvfs-mtp l3afpad lightdm lightdm-gtk-greeter mpv network-manager-applet noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra nvidia-dkms nvidia-settings p7zip pacman-contrib pavucontrol picom polkit-gnome polybar pulseaudio pulseaudio-bluetooth sudo sxhkd thunar thunar-archive-plugin thunar-media-tags-plugin thunar-volman ttf-hack ttf-nerd-fonts-symbols tumbler unrar xarchiver xdg-user-dirs xorg-server
#pacman -S ark bluedevil breeze-gtk curl dolphin drkonqi efibootmgr ffmpegthumbs git grub gwenview icoutils kde-gtk-config kdeplasma-addons khotkeys konsole kvantum-qt5 kwallet-pam kwrite kwrited mpv noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra nvidia-dkms nvidia-settings p7zip pacman-contrib partitionmanager plasma-desktop plasma-nm plasma-pa plasma-systemmonitor powerdevil pulseaudio pulseaudio-bluetooth sddm-kcm unrar sudo ttf-nerd-fonts-symbols xdg-desktop-portal-kde xdg-user-dirs xorg-server
#VM STUFF: qemu virt-manager virt-viewer dnsmasq vde2 bridge-utils openbsd-netcat edk2-ovmf

# ADDITIONALLY, INSTALL (using paru): jamesdsp qview tauon-music-box vscodium-bin

#ADD MORE CORES TO MAKEPKG
sed -i "s/#MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j8\"/" /etc/makepkg.conf

#CREATE USER
echo --CREATE NORMAL USER--
read -p "Username: " uname
useradd -m -G wheel $uname
passwd $uname

#SUDO PERMS
EDITOR=vim visudo

#ENABLE DM AND NETWORKING
systemctl enable sddm
systemctl enable NetworkManager
systemctl enable bluetooth

rm 2
